### PR TITLE
 	Use built in session handler interface

### PR DESCRIPTION
**Pull request by live627**
Rebase this so no merge commit is added

Selenium tests are broken.

Idea:
- rename development to develop-1.1
- push this to develop

### CODE REVIEW

**Comment by emanuele45** [comment]
I'm pretty sure this is another bug found while removing all the deprecated code, the condition for php 5.6.27+ is pointless as it is (I mean in 1.1).
I'll check it tomorrow.

**Comment by emanuele45** [comment]
Regarding the branches: as soon as RC1 is ready (and I really hope it will be **soon**), the idea is to branch 1.1-release (or something like that, so that we can keep adding the (hopefully) small fixes necessary for the release there) and keep development for 2.0, later when 1.1 is released it will be merged into master.

**Comment by emanuele45** [comment]
Was that coming to my repo?
I lost it entirely... sorry!! :sob:

**Comment by live627** [comment]
I forgot I made this...

Cherry picking time!

**Pull request closed without merging**
